name: northwind-polyglot

services:

- name: postgres
  image: debezium/postgres
  env_file:
    - .env
  bindings:
    - port: 5432
      connectionString: Server=${host};Port=${port};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
  tags:
    - inf

- name: product-catalog
  dockerFile: product-catalog/Dockerfile
  # image: product-catalog:latest
  env_file:
    - .env
  bindings:
  - name: http
    protocol: http
    containerPort: 5002
    port: 5002
  - name: tcp
    protocol: tcp
    containerPort: 50002
    port: 50002

- name: sale-payment
  project: sale-payment/sale-payment.csproj
  env_file:
    - .env
  bindings:
    - port: 5003
