name: northwind-polyglot
# extensions:
# - name: dapr
#   log-level: debug
#   components-path: "./components/"

services:

- name: postgres
  image: debezium/postgres
  env_file:
    - .env
  bindings:
    - port: 5432
      connectionString: Server=${host};Port=${port};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
  tags:
    - inf

# - name: zookeeper
#   image: debezium/zookeeper:latest
#   bindings:
#     - name: "2181"
#       containerPort: 2181
#       port: 2181
#     - name: "2888"
#       containerPort: 2888
#       port: 2888
#     - name: "3888"
#       containerPort: 3888
#       port: 3888
#   tags:
#     - inf

# - name: kafka
#   image: debezium/kafka:latest
#   env:
#     - ZOOKEEPER_CONNECT=zookeeper:2181
#     - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
#     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://kafka:9092
#     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#     - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
#     - KAFKA_ZOOKEEPER_SESSION_TIMEOUT=6000
#     - KAFKA_RESTART_ATTEMPTS=10
#     - KAFKA_RESTART_DELAY=5
#     - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0
#     - KAFKA_ADVERTISED_HOST_NAME=localhost
#   bindings:
#     - containerPort: 9092
#       port: 9092
#   tags:
#     - inf

# - name: schema-registry
#   image: confluentinc/cp-schema-registry:6.1.0
#   env:
#     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
#     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
#     - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
#   bindings:
#     - protocol: http
#       containerPort: 8081
#       port: 8081
#   tags:
#     - inf

# - name: kafdrop
#   image: obsidiandynamics/kafdrop:3.27.0
#   env:
#     - ZOOKEEPER_CONNECT=zookeeper:2181
#     - KAFKA_BROKERCONNECT=kafka:9092
#     - SCHEMAREGISTRY_CONNECT=http://schema-registry:8081
#     - JVM_OPTS=-Xms32M -Xmx64M
#     - SERVER_SERVLET_CONTEXTPATH="/"
#   bindings:
#     - protocol: http
#       containerPort: 9000
#       port: 9000
#   tags:
#     - inf

- name: product-catalog
  dockerFile: product-catalog/Dockerfile
  # image: product-catalog:latest
  env_file:
    - .env
  bindings:
  - name: http
    protocol: http
    containerPort: 5002
    port: 5002
  - name: tcp
    protocol: tcp
    containerPort: 50002
    port: 50002

- name: sale-payment
  project: sale-payment/sale-payment.csproj
  env_file:
    - .env
  bindings:
    - port: 5003

- name: shipping
  dockerFile: shipping/Dockerfile.dev
  # dockerFile: shipping/Dockerfile
  # image: shipping:0.0.1-SNAPSHOT
  env_file:
    - .env
  bindings:
  - name: http
    protocol: http
    containerPort: 5004
    port: 5004
