name: northwind-polyglot

services:

- name: postgres
  image: debezium/postgres
  env_file:
    - .env
  bindings:
    - port: 5432
      connectionString: Server=${host};Port=${port};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
  tags:
    - inf

- name: product-catalog
  dockerFile: product-catalog/Dockerfile
  env_file:
    - .env
  bindings:
  - protocol: http
    port: 5002
